# PLEASE STOP!
# DO NOT EDIT THIS FILE OR DELETE THIS FILE
# Create a new config.py file in same directory and import, then extend this class.

import os
from typing import Set

from telethon.tl.types import ChatBannedRights
from validators.url import url

# إضافة المتغير الناقص لحل مشكلة الـ Startup
heroku_var = False

class Config(object):
    LOGGER = True
    PORT = os.environ.get("PORT", None)
    
    # MUST NEEDED VARS
    ALIVE_NAME = os.environ.get("ALIVE_NAME", None)
    APP_ID = int(os.environ.get("APP_ID", 6))
    API_HASH = os.environ.get("API_HASH") or None
    
    # تحسين جلب رابط قاعدة البيانات ليدعم Fly.io بشكل مباشر
    DB_URI = os.environ.get("DATABASE_URL") or os.environ.get("DB_URI", None)
    
    STRING_SESSION = os.environ.get("STRING_SESSION", None)
    TG_BOT_TOKEN = os.environ.get("TG_BOT_TOKEN") or os.environ.get("TG_BOT_TOKEN_BF_HER", None)
    TG_BOT_USERNAME = None
    TZ = os.environ.get("TZ", "Asia/Baghdad")
    UPSTREAM_REPO = os.environ.get("UPSTREAM_REPO", "https://github.com/RepthonArabic/Repthon")
    
    EXTERNAL_REPO = os.environ.get("EXTERNAL_REPO", None)
    if EXTERNAL_REPO and (EXTERNAL_REPO.lower() != "no") and not url(EXTERNAL_REPO):
        EXTERNAL_REPO = "https://github.com/TgCatUB/CatPlugins"
    
    OLDZED = os.environ.get("OLDZED", "no")
    OLDZED = bool(OLDZED and (OLDZED.lower() != "no"))

    PRIVATE_GROUP_BOT_API_ID = int(os.environ.get("PRIVATE_GROUP_BOT_API_ID") or 0)
    PRIVATE_GROUP_ID = int(os.environ.get("PRIVATE_GROUP_ID") or 0)
    FBAN_GROUP_ID = int(os.environ.get("FBAN_GROUP_ID") or 0)
    PRIVATE_CHANNEL_BOT_API_ID = int(os.environ.get("PRIVATE_CHANNEL_BOT_API_ID") or 0)

    # التعديل الجذري هنا: تغيير False إلى None لحل مشكلة الـ ValueError
    HEROKU_API_KEY = os.environ.get("HEROKU_API_KEY", None)
    HEROKU_APP_NAME = os.environ.get("HEROKU_APP_NAME", None)

    OWNER_ID = int(os.environ.get("OWNER_ID") or 0)
    PM_LOGGER_GROUP_ID = int(os.environ.get("PM_LOGGER_GROUP_ID") or os.environ.get("PM_LOGGR_BOT_API_ID") or 0)

    # فـارات ريبـــثون
    CUSTOM_ALIVE_TEXT = os.environ.get("CUSTOM_ALIVE_TEXT", None)
    CUSTOM_ALIVE_EMOJI = os.environ.get("CUSTOM_ALIVE_EMOJI", None)
    CUSTOM_ALIVE_EMZED = os.environ.get("CUSTOM_ALIVE_EMZED", None)
    CUSTOM_PMPERMIT = os.environ.get("CUSTOM_PMPERMIT", None)
    ALIVE_PIC = os.environ.get("ALIVE_PIC", None)
    BOT_PIC = os.environ.get("BOT_PIC", None)
    REP_MEDIA = os.environ.get("REP_MEDIA", None)
    BOT_HANDLER = os.environ.get("BOT_HANDLER", "^;")
    PMPERMIT_PIC = os.environ.get("PMPERMIT_PIC", None)
    DIGITAL_PIC = os.environ.get("DIGITAL_PIC", None)
    DEFAULT_PIC = os.environ.get("DEFAULT_PIC", None)
    DEFAULT_BIO = os.environ.get("DEFAULT_BIO", None)
    DEFAULT_NAME = os.environ.get("DEFAULT_NAME", None)
    BA_FN = os.environ.get("BA_FN", "𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵𝟬")
    CUSTOM_PMPERMIT_TEXT = os.environ.get("CUSTOM_PMPERMIT_TEXT", None)
    VCMODE = os.environ.get("VCMODE", "false")
    VCMODE = bool(VCMODE and (VCMODE.lower() != "false"))
    VC_SESSION = os.environ.get("VC_SESSION", None)

    PLUGIN_CHANNEL = int(os.environ.get("PLUGIN_CHANNEL") or 0)
    TELEGRAPH_SHORT_NAME = os.environ.get("TELEGRAPH_SHORT_NAME", "Repthon")
    THUMB_IMAGE = os.environ.get("THUMB_IMAGE", "https://telegra.ph/file/2be69528a8ae9eb43fc40.jpg")
    NO_LOAD = list(os.environ.get("NO_LOAD", "").split())
    COMMAND_HAND_LER = os.environ.get("COMMAND_HAND_LER", r".")
    SUDO_COMMAND_HAND_LER = os.environ.get("SUDO_COMMAND_HAND_LER", r".")
    TMP_DOWNLOAD_DIRECTORY = os.environ.get("TMP_DOWNLOAD_DIRECTORY", "downloads")
    TEMP_DIR = os.environ.get("TEMP_DIR", "./temp/")
    ANTISPAMBOT_BAN = os.environ.get("ANTISPAMBOT_BAN", False)
    FINISHED_PROGRESS_STR = os.environ.get("FINISHED_PROGRESS_STR", "▰")
    UNFINISHED_PROGRESS_STR = os.environ.get("UNFINISHED_PROGRESS_STR", "▱")

    SCREEN_SHOT_LAYER_ACCESS_KEY = os.environ.get("SCREEN_SHOT_LAYER_ACCESS_KEY", None)
    OPEN_WEATHER_MAP_APPID = os.environ.get("OPEN_WEATHER_MAP_APPID", None)
    IBM_WATSON_CRED_URL = os.environ.get("IBM_WATSON_CRED_URL", None)
    IBM_WATSON_CRED_PASSWORD = os.environ.get("IBM_WATSON_CRED_PASSWORD", None)
    IPDATA_API = os.environ.get("IPDATA_API", None)
    OCR_SPACE_API_KEY = os.environ.get("OCR_SPACE_API_KEY", None)
    GENIUS_API_TOKEN = os.environ.get("GENIUS_API_TOKEN", None)
    REM_BG_API_KEY = os.environ.get("REM_BG_API_KEY", None)
    CURRENCY_API = os.environ.get("CURRENCY_API", None)
    G_DRIVE_CLIENT_ID = os.environ.get("G_DRIVE_CLIENT_ID", None)
    G_DRIVE_CLIENT_SECRET = os.environ.get("G_DRIVE_CLIENT_SECRET", None)
    G_DRIVE_FOLDER_ID = os.environ.get("G_DRIVE_FOLDER_ID", None)
    G_DRIVE_DATA = os.environ.get("G_DRIVE_DATA", None)
    G_DRIVE_INDEX_LINK = os.environ.get("G_DRIVE_INDEX_LINK", None)
    TG_2STEP_VERIFICATION_CODE = os.environ.get("TG_2STEP_VERIFICATION_CODE", None)
    WATCH_COUNTRY = os.environ.get("WATCH_COUNTRY", "IN")
    BIO_PREFIX = os.environ.get("BIO_PREFIX", None)
    LASTFM_API = os.environ.get("LASTFM_API", None)
    LASTFM_SECRET = os.environ.get("LASTFM_SECRET", None)
    LASTFM_USERNAME = os.environ.get("LASTFM_USERNAME", None)
    LASTFM_PASSWORD_PLAIN = os.environ.get("LASTFM_PASSWORD", None)
    SPOTIFY_CLIENT_ID = os.environ.get("SPOTIFY_CLIENT_ID", None)
    SPOTIFY_CLIENT_SECRET = os.environ.get("SPOTIFY_CLIENT_SECRET", None)
    SPAMWATCH_API = os.environ.get("SPAMWATCH_API", None)
    RANDOM_STUFF_API_KEY = os.environ.get("RANDOM_STUFF_API_KEY", None)
    GITHUB_ACCESS_TOKEN = os.environ.get("GITHUB_ACCESS_TOKEN", None)
    GIT_REPO_NAME = os.environ.get("GIT_REPO_NAME", None)
    DEEP_AI = os.environ.get("DEEP_AI", None)

    MAX_MESSAGE_SIZE_LIMIT = 4095
    LOAD = []
    ANTI_FLOOD_WARN_MODE = ChatBannedRights(until_date=None, view_messages=None, send_messages=True)
    CHROME_BIN = os.environ.get("CHROME_BIN", "/app/.apt/usr/bin/google-chrome")
    CHROME_DRIVER = os.environ.get("CHROME_DRIVER", "/app/.chromedriver/bin/chromedriver")
    GROUP_REG_SED_EX_BOT_S = os.environ.get("GROUP_REG_SED_EX_BOT_S", r"(regex|moku|BananaButler_|rgx|l4mR)bot")
    COUNTRY = str(os.environ.get("COUNTRY", ""))
    TZ_NUMBER = int(os.environ.get("TZ_NUMBER", 1))
    UPSTREAM_REPO_BRANCH = os.environ.get("UPSTREAM_REPO_BRANCH", "master")
    SUDO_USERS: Set[int] = set()
    ZQ_LOLOGO = None
    BOTLOG = False
    BOTLOG_CHATID = 0
    EXTERNAL_REPOBRANCH = os.environ.get("EXTERNAL_REPOBRANCH", "main")
    OLDZED_REPO = os.environ.get("OLDZED_REPO", "https://github.com/RepthonArabic/RepthonAr")
    if OLDZED_REPO and not url(OLDZED_REPO):
        OLDZED_REPO = "https://github.com/RepthonArabic/RepthonAr"
    OLDZED_REPOBRANCH = os.environ.get("OLDZED_REPOBRANCH", "oldzed")
    VC_REPO = os.environ.get("VC_REPO", "https://github.com/RepthonArabic/RepVcPlayer")
    VC_REPOBRANCH = os.environ.get("VC_REPOBRANCH", "zvcplayer")

class Production(Config):
    LOGGER = False

class Development(Config):
    LOGGER = True
